In [ ]:
import pandas as pd  # Naive Bayes classifier
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [7]:
dataset.head()

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0  15624510   19            19000          0         True
1  15810944   35            20000          0         True
2  15668575   26            43000          0        False
3  15603246   27            57000          0        False
4  15804002   19            76000          0         True

In [8]:
#  Remove user_id Column
# dataset=dataset.drop("User ID",axis=1)
dataset = dataset.drop("User ID", axis=1)

In [9]:
dataset.head()

Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0         True
1   35            20000          0         True
2   26            43000          0        False
3   27            57000          0        False
4   19            76000          0         True

In [10]:
dataset["Purchased"].value_counts()


Purchased
0    257
1    143
Name: count, dtype: int64

In [13]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [14]:
indep.shape

(400, 3)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size=0.3, random_state=0)

In [39]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB, ComplementNB, CategoricalNB


In [28]:
def CallGaussianNB():
    data = {}
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)

    from sklearn.metrics import confusion_matrix, classification_report
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    # classification report
    clf_report = classification_report(y_test, y_pred)
    print("========= Gaussin Naive Bayes Classifier ===========")
    print("Confusion Matrix :", cm )
    print("Classification Report:", clf_report)
    data = {"Algorithm": "GaussianNB", "Confusion Matrix": cm, "Classification Report": clf_report}
    return data

print(CallGaussianNB())


[[74  5]
 [ 8 33]]
========= Gaussin Naive Bayes Classifier ===========
Confusion Matrix : [[74  5]
 [ 8 33]]
Classification Report:               precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120

{'Algorithm': 'GaussianNB', 'Confusion Matrix': array([[74,  5],
       [ 8, 33]], dtype=int64), 'Classification Report': '              precision    recall  f1-score   support\n\n           0       0.90      0.94      0.92        79\n           1       0.87      0.80      0.84        41\n\n    accuracy                           0.89       120\n   macro avg       0.89      0.87      0.88       120\nweighted avg       0.89      0.89      0.89       120\n'}


In [30]:
def callMultinomialNB():
    data = {}
    classifier = MultinomialNB()
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)

    from sklearn.metrics import confusion_matrix, classification_report
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    # classification report
    clf_report = classification_report(y_test, y_pred)
    print("========= Multinomial Naive Bayes Classifier ===========")
    print("Confusion Matrix :", cm )
    print("Classification Report:", clf_report)
    data = {"Algorithm": "MultinomialNB", "Confusion Matrix": cm, "Classification Report": clf_report}
    return data

print(callMultinomialNB())


[[68 11]
 [28 13]]
========= Multinomial Naive Bayes Classifier ===========
Confusion Matrix : [[68 11]
 [28 13]]
Classification Report:               precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120

{'Algorithm': 'MultinomialNB', 'Confusion Matrix': array([[68, 11],
       [28, 13]], dtype=int64), 'Classification Report': '              precision    recall  f1-score   support\n\n           0       0.71      0.86      0.78        79\n           1       0.54      0.32      0.40        41\n\n    accuracy                           0.68       120\n   macro avg       0.62      0.59      0.59       120\nweighted avg       0.65      0.68      0.65       120\n'}


In [34]:
def callBernoulliNB():
    data = {}
    classifier = BernoulliNB()
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)

    from sklearn.metrics import confusion_matrix, classification_report
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    # classification report
    clf_report = classification_report(y_test, y_pred)
    print("========= Bernoulli Naive Bayes Classifier ===========")
    print("Confusion Matrix :", cm )
    print("Classification Report:", clf_report)
    data = {"Algorithm": "BernoulliNB", "Confusion Matrix": cm, "Classification Report": clf_report}
    return data
    # return "Success"

print(callBernoulliNB())

[[79  0]
 [41  0]]
========= Bernoulli Naive Bayes Classifier ===========
Confusion Matrix : [[79  0]
 [41  0]]
Classification Report:               precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120

{'Algorithm': 'BernoulliNB', 'Confusion Matrix': array([[79,  0],
       [41,  0]], dtype=int64), 'Classification Report': '              precision    recall  f1-score   support\n\n           0       0.66      1.00      0.79        79\n           1       0.00      0.00      0.00        41\n\n    accuracy                           0.66       120\n   macro avg       0.33      0.50      0.40       120\nweighted avg       0.43      0.66      0.52       120\n'}


C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

In [41]:
def callComplementNB():
    data = {}
    classifier = ComplementNB()
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)

    from sklearn.metrics import confusion_matrix, classification_report
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    # classification report
    clf_report = classification_report(y_test, y_pred)
    print("========= Complement Naive Bayes Classifier ===========")
    print("Confusion Matrix :", cm )
    print("Classification Report:", clf_report)
    data = {"Algorithm": "ComplementNB", "Confusion Matrix": cm, "Classification Report": clf_report}
    return data
    # return "Success"

print(callComplementNB())

[[42 37]
 [20 21]]
========= Complement Naive Bayes Classifier ===========
Confusion Matrix : [[42 37]
 [20 21]]
Classification Report:               precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120

{'Algorithm': 'ComplementNB', 'Confusion Matrix': array([[42, 37],
       [20, 21]], dtype=int64), 'Classification Report': '              precision    recall  f1-score   support\n\n           0       0.68      0.53      0.60        79\n           1       0.36      0.51      0.42        41\n\n    accuracy                           0.53       120\n   macro avg       0.52      0.52      0.51       120\nweighted avg       0.57      0.52      0.54       120\n'}


In [40]:
def callCategoricalNB():
    data = {}
    classifier = CategoricalNB()
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)

    from sklearn.metrics import confusion_matrix, classification_report
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    # classification report
    clf_report = classification_report(y_test, y_pred)
    print("========= Categorical Naive Bayes Classifier ===========")
    print("Confusion Matrix :", cm )
    print("Classification Report:", clf_report)
    data = {"Algorithm": "ComplementNB", "Confusion Matrix": cm, "Classification Report": clf_report}
    return data
    # return "Success"

print(callCategoricalNB())

[[76  3]
 [ 9 32]]
========= Categorical Naive Bayes Classifier ===========
Confusion Matrix : [[76  3]
 [ 9 32]]
Classification Report:               precision    recall  f1-score   support

           0       0.89      0.96      0.93        79
           1       0.91      0.78      0.84        41

    accuracy                           0.90       120
   macro avg       0.90      0.87      0.88       120
weighted avg       0.90      0.90      0.90       120

{'Algorithm': 'ComplementNB', 'Confusion Matrix': array([[76,  3],
       [ 9, 32]], dtype=int64), 'Classification Report': '              precision    recall  f1-score   support\n\n           0       0.89      0.96      0.93        79\n           1       0.91      0.78      0.84        41\n\n    accuracy                           0.90       120\n   macro avg       0.90      0.87      0.88       120\nweighted avg       0.90      0.90      0.90       120\n'}
